### ISSUE TITLE
Wrong beneficiary in rgb transfer step

### ISSUE THREAD

**Issue by crisdut** [RGB-WG/rgb#69] opened 2023-12-22 06:03 UTC
### **Description**
**Version:** https://github.com/RGB-WG/rgb/pull/39/commits/62b5009146b363553493e2a3a9b516866f54c78c

When we try running the transfer command below, the cli returns: `Error: taproot output doesn't specify internal key.` 

```
rgb  -w default transfer rgb:28hM4....f86n 100 ./transfer.rgb
```

After investigate, I noticed that the transfer step mistakenly uses the invoice beneficiary, transferring all the satoshis to him, which ends up producing an incorrect output in the PSBT. 

**Type:** bug

**Comment by shuimuliang** [comment] 2023-12-22 06:36
Yes, it is reproduced by building https://github.com/RGB-WG/rgb cli, branch v0.11.

**Comment by dr-orlovsky** [comment] 2023-12-25 01:05
This issue was unrelated to the beneficiary. It was caused by the fact that PSBT had invalid order of outputs, with the first taproot output being an external pay (meaning it can't be tapret-tweaked).

Fixed in https://github.com/RGB-WG/rgb/pull/39/commits/3961b4de87f27acc8fca5cc2fb9e4864ecaec42a#diff-1526fe65eedcfd110d7eead9254a96a1fb18fdfe9d22822ec6517a233a77162bR252-R253

**Closed** 2023-12-25 01:05 UTC
