### ISSUE TITLE
negative balance when syncing wallet

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#176] opened 2024-04-22 15:48 UTC
Using commit `ac43eb2` plus a cargo update to include the latest fixes, I sometimes run into an issue.

This is what I'm doing:
- issue a NIA asset on wallet 1
- send some NIA assets from wallet 1 to wallet 2
- send some more NIA assets from wallet 1 to wallet 2
- send some NIA assets from wallet 2 to wallet 1

All operations are carried out using `opret1st` closing method, all invoices are blinded.

During the last transfer, wallet 2 fails to sync with:
```
Loading descriptor from wallet wallet_2 ... success
Syncing keychain 0 .......... keychain 1 .......... keychain 9 .............thread 'main' panicked at ~/.cargo/git/checkouts/bp-wallet-997f3c057e1b59f2/e05f6c7/src/data.rs:410:55:
negative balance: TryFromIntError(())
```

Here is the whole data dir for wallet 2, including consignments for previous transfers:
[wallet2_data.tar.gz](https://github.com/RGB-WG/rgb/files/15065406/wallet2_data.tar.gz)

**Comment by dr-orlovsky** [comment] 2024-06-09 16:46
This is entire mystery for me why this happens. I will wait on the confirmation that the issue is still in the released beta 6 and will pay more attention in fixing it. I believe it is a pure command-line tool issue unrelated to a more deep levels

**Comment by dr-orlovsky** [comment] 2024-07-11 08:52
Can we verify that the issue is still there with the most recent `master` branches?

**Comment by Crayon-Shin-chan-1024** [comment] 2024-07-11 09:22
> Can we verify that the issue is still there with the most recent `master` branches?

i have testet it, it fixed by https://github.com/BP-WG/bp-wallet/pull/35

**Comment by dr-orlovsky** [comment] 2024-07-17 08:31
@nicbus can you pls confirm that the bug is fixed

**Closed** 2024-07-17 15:59 UTC
Labels: bug, question
