### ISSUE TITLE
operation slow-down

### ISSUE THREAD

**Issue by nicbus** [RGB-WG/rgb#20] opened 2023-07-04 13:27 UTC
Following the development of RGB crates we noticed a significant slow-down of some RGB operations.

This can clearly be felt when running in debug mode and has been spotted both using our `rgb-lib` and `rgb-sandbox` projects.

I prepared two `rgb-sandbox` branches, which use different dependencies and time the `rgb import` and `rgb issue` commands, to show the difference:
- [v0.10_fast](https://github.com/nicbus/rgb-sandbox/tree/v0.10_fast) uses older dependencies (plus some small fixes)
- [v0.10_slow](https://github.com/nicbus/rgb-sandbox/tree/v0.10_slow) uses the current master

Comparing runs with those branches I get the following results, which show a greater than 10x time increase:
- v0.10_fast
```
    rgb import:   372 ms
    rgb issue:    969 ms
```
- v0.10_slow
```
    rgb import:  5604 ms
    rgb issue:  11628 ms
```

For reference, these are the results when building in release mode, which still show a ~5x time increase:
- v0.10_fast
```
    rgb import:    69 ms
    rgb issue:     94 ms
```
- v0.10_slow
```
    rgb import:   305 ms
    rgb issue:    590 ms
```

It seems to me it's worth investigating the cause of such a sizable slow-down.

Here's a list of the main differences in dependencies between the two versions:
| crate | v0.10_fast | v0.10_slow |
| --- | --- | --- |
| rgb-core | 0.10.4 | 1de67f7b |
| rgb-wallet / rgb-std | d90868a7 | 79eb02cc |
| strict_encoding | 2.3.0 | 2.4.0 |
| strict_types | 1.3.0 | 1.4.0 |

PS: I don't think this is the project where the "bug" is, but opening here as it's the main CLI entrypoint, what `rgb-sandbox` uses and what I changed to show the difference.

**Comment by dr-orlovsky** [comment] 2023-07-05 12:17
This is very strange and should be important to fix! Thank you for the provided benchmarking. I will be comparing the provided commits and will try to see which changes may introduce the slowdown. We also need to keep in mind that the slowdown may be caused by some changes in the dependencies we are using and did update between those commits...

**Comment by nicbus** [comment] 2023-07-06 08:17
I prepared a flamegraph for each of the timed `rgb-contracts` commands above (import/issue on slow/fast branches in debug/release mode).

These will hopefully help troubleshoot the issue, IMO especially by comparing between slow vs fast branches in debug mode.

[flamegraphs.zip](https://github.com/RGB-WG/rgb/files/11966018/flamegraphs.zip)

**Comment by dr-orlovsky** [comment] 2023-07-06 09:03
It seems the reason for the issue is this one: https://github.com/strict-types/strict-types/issues/21#issuecomment-1623241814

Not sure what to actually do here...

**Comment by dr-orlovsky** [comment] 2023-07-08 19:35
Closed as described in https://github.com/strict-types/strict-types/issues/21

**Comment by nicbus** [comment] 2023-07-10 12:33
Timed the `v0.10_slow` sandbox branch again, using `rgb-contracts` commit `32dbfac`

In debug I get:
```
rgb import:  450 ms
rgb issue:   419 ms

```
and in release:
```
rgb import:   81 ms
rgb issue:    41 ms
```

I think it's safe to say that the slowness has been addressed and speed is back to previous levels.

**Closed** 2023-07-10 13:38 UTC
Labels: bug, help wanted, question
